[package]
name = "day2"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.25"

[dependencies.intcode]
path = "../intcode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
